### ISSUE TITLE
Cannot find ap_secret.h

### ISSUE THREAD

**Issue by FatBeard** [deadbok/ntp-led-clock#1]
Hi,

having a few issues compiling this. It's saying cannot find "ap_secret.h". Presumably you didn't check it in as it has passwords, but can you give me the format of the file. thanks.

**Comment by deadbok** [comment]
You are right. It is supposed to be obsolete, when the project is done. In the meantime I will paste it here:

    /*
     * Secrets used to connect to the WIFI network during test.
     */

    #ifndef _AP_SECRET_H_
    #define _AP_SECRET_H_

    #ifndef STASSID
    #define STASSID "***SSID***"
    #define STAPSK "password"
    #endif

    #endif
